[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path = 'forge-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
test = 'test'
solc = '0.8.26'
fs_permissions = [
    { access = 'read', path = './' },
    { access = 'read-write', path = './deploy-out' },
]
evm_version = 'cancun'

[rpc_endpoints]
# Comment out for local development (testing requires 0xSplit forks — will add Mock soon)
# pin fork by using --fork-block-number 19042069 to reduce wait time
mainnet = "https://rpc.ankr.com/eth"
testnet = "${TESTNET_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
